# Generated by Django 4.2.1 on 2024-07-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_document_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='book_content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ebook.bookcontent'),
            preserve_default=False,
        ),
    ]
